console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

    [[blocks.segments]]
        type = 'path'
        style = 'plain'
        background = 'transparent'
        foreground = 'blue'
        template = '{{ .Path }}'

        [blocks.segments.properties]
            style = 'full'

    [[blocks.segments]]
        type = 'git'
        style = 'plain'
        foreground = 'magenta'
        background = 'transparent'
        template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .Behind 0 }} ⇣{{ end }}{{ if gt .Ahead 0 }} ⇡{{end}}'

        [blocks.segments.properties]
            branch_icon = ''
            comit_icon = '@'
            fetch_status = true

    [[blocks.segments]]
        type = 'text'
        style = 'plain'
        foreground = 'magenta'
        background = 'transparent'
        template = ' ❯'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
        threshold = 100
        style = 'roundrock'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'gray'
    background = 'transparent'

    [blocks.segments.properties]
        time_format = '15:04:05'



[transient_prompt]
    foreground = 'magenta'
    background = 'transparent'
    template = '❯ '
